### PR TITLE
Updating firebase-admin to 8.1.0 and google-cloud-logging-logback to 0.123.5-alpha

### PR DESCRIPTION
**Pull request by ylhn15**
Updating dependencies to their newest version.

### CODE REVIEW

**Comment by dazld** [comment]
@ylhn15 did you have any issues running with these deps updated?

**Comment by ylhn15** [comment]
No, everything works fine for me

**Comment by lurodrigo** [comment]
@dazld approved. But I don't have any clj tooling installed anymore (and time), so I recommend hosting the updated package somehow.

**Comment by dazld** [comment]
A git url as a dep works for us, thank you.

**Pull request merged**
